Algoritmo "notas"

Var


 a,b,c, menor : inteiro
 


Inicio

 Escreval ("Digite o primeiro numero")
 leia (a)
 Escreval ("Digite o segundo numero")
 leia (b)
 Escreval ("Digite o terceiro numero")
 leia (c)
 
 Se (a < b)  e(a < c) entao
 menor <- a
 senao
 Se b < c entao
 menor <- b
 Senao
  menor <- c

 fimse
 fimse

 Escreval (" o menor valor é ", menor)

Fimalgoritmo